Created FDMI high level decomposition .md page
Seagate/cortx pull request #1323
Opened 2021-11-12 14:09 UTC by swatid-seagate

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2021-11-14 11:57 UTC, huanghua78 commented
Please rename all `xyratex` to `seagate`

2021-11-15 17:24 UTC, johnbent requested changes
Hey Swati. Good job on making some initial FDMI documents! However, FDMI documents should be in the motr repo. @lia54 can help since she is also working on FDMI documentation.

2021-11-15 17:24 UTC, johnbent commented on Community_Roadmap.md
> -            <td> </td>
This should not be in a PR about FDMI.

2021-11-15 17:24 UTC, johnbent commented on QUICK_START.md
> +    1. On a single node: [LINK](doc/ova/2.0.0/PI-3/CORTX_on_Open_Virtual_Appliance_PI-3.rst)
This change should not be in a PR about FDMI.

2021-11-15 17:24 UTC, johnbent commented on QUICK_START.md
> +    1. Run it on a single node: [LINK](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-3/CORTX_on_Open_Virtual_Appliance_PI-3.rst)
This change should not be in a PR about FDMI.

2021-12-02 13:05 UTC, r-wambui commented
@swatid-seagate For git workflow, it's best to create a PR related to each task/feature/bug, etc. The PR title you have currently is FDMI, so any file changes should only reflect anything about FDMI; however, you have other changes on the PR that relate to the quick start guide and not fdmi.
Could you please create multiple PRs where each relates to a given task e.g

1. for fdmi
2. for community roadmap
3. for quick start guide.

Doing this makes reviewing easier. You could also do the same for the PR in motr repo.

2022-01-05 16:59 UTC, r-wambui commented
@swatid-seagate Could you please close this pull request(PR), if you have already transferred the changes to motr repo and the PR is no longer required.

2022-01-19 10:14 UTC, closed without merging