Update README.rst
Seagate/cortx pull request #1356
Opened 2021-12-01 17:53 UTC by novium258

Signed-off-by: Rachel N <rachel.novak@seagate.com>

2021-12-02 05:21 UTC, mukul-seagate11 requested changes

2021-12-02 05:21 UTC, mukul-seagate11 commented on doc/meetings/README.rst
> +Please `click here < https://cortx.link/CORTX-MTAs>`_ to see the event page.
Link is not accessible, please fix

2021-12-02 05:21 UTC, mukul-seagate11 requested changes

2021-12-02 05:21 UTC, mukul-seagate11 commented on doc/meetings/README.rst
> +#. November 4 2021: Liana Valdes discussed an exciting new addition to the CORTX project. FDMI allows data scientists to subscribe to event notifications and then perform custom manipulations or anal
PDF Link is broken, please fix

2021-12-08 17:16 UTC, johnbent approved these changes

2021-12-08 17:17 UTC, merged