Updated Quick start guide.
Seagate/cortx pull request #1383
Opened 2022-01-12 10:39 UTC by swatid-seagate

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2022-01-12 18:02 UTC, johnbent requested changes

2022-01-18 07:33 UTC, swatid-seagate commented on QUICK_START.md
> +    1. Run it on a AWS: [LINK](https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)
Modified the file according to your suggestion and updated the PR.

2022-01-18 13:02 UTC, mukul-seagate11 approved these changes
looks good

2022-01-18 20:21 UTC, johnbent requested changes

2022-01-18 20:21 UTC, johnbent commented on QUICK_START.md
> +1. Run it on AWS in Kubernetes: [LINK](https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)
instead of 'in Kubernetes' it should say 'using Kubernetes'

2022-01-18 20:21 UTC, johnbent commented on QUICK_START.md
> +2. Build entire CORTX into binaries: [LINK](./doc/community-build/docker/cortx-all/README.md)
This shouldn't be a 2. All numbers should be 1 and the github server will render them automatically when they serve the page.

2022-01-18 20:21 UTC, johnbent commented on QUICK_START.md
> -3. Build just the datapath (motr + S3) from the source: [LINK](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)
This shouldn't be a 3, should be a 1

2022-01-18 20:21 UTC, johnbent commented on QUICK_START.md
> -3. Build just the datapath (motr + S3) from the source: [LINK](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)
Oh, I see you are removing this so the numbering here doesn't matter.

2022-01-19 10:15 UTC, closed without merging