issue-1407: Verified this document works for Virtual Box
Seagate/cortx pull request #1472
Opened 2022-03-25 11:02 UTC by alfhad

I have successfully tested the steps given in this document with Virtual Box.

Signed-off-by: alfhad <fahadshah2411@gmail.com>

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2022-03-28 11:56 UTC, hessio commented
resolves #1472

2022-03-28 18:43 UTC, johnbent requested changes

2022-03-29 05:01 UTC, alfhad commented on doc/ova/2.0.0/PI-5/CORTX_on_Open_Virtual_Appliance_PI-5.rst
> +- Mar 25, 2022: Sayed Alfhad Shah (fahadshah2411@gmail.com) on a Windows and Fedora laptop with Oracle Virtual Box 6.1.
Done!

2022-04-04 17:06 UTC, johnbent approved these changes

2022-04-04 17:06 UTC, merged