CORTX-30701 Community Build steps improvements.
Seagate/cortx pull request #1489
Opened 2022-04-20 15:20 UTC by shailesh-vaidya

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2022-04-21 04:00 UTC, mukul-seagate11 requested changes

2022-04-21 05:27 UTC, shailesh-vaidya commented on doc/community-build/docker/cortx-all/README.md
> +2.  Please checkout **main** branch for generating CORTX packages. Use below command for checkout.
Done. Please review

2022-04-21 05:28 UTC, shailesh-vaidya commented on doc/community-build/docker/cortx-all/README.md
> +7. Clone [cortx-re](https://github.com/Seagate/cortx-re) repository using below commands,
Done. Please review

2022-04-21 05:28 UTC, shailesh-vaidya commented on doc/community-build/docker/cortx-all/README.md
> +    - Use below command to build cortx-all image. Enure you are in `cortx-re/docker/cortx-deploy/` directory:
Done. Please review

2022-04-21 05:29 UTC, shailesh-vaidya commented on doc/community-build/docker/cortx-all/README.md
> +    Ensure that container is started and we can download RELEASE.INFO
Downloading RELEASE.INFO is to just test that nginx container is running it's not required in our workflow. Maybe we can use. 
`Ensure that container is started and validate by downloading RELEASE.INFO`

2022-04-21 13:09 UTC, mukul-seagate11 commented on doc/community-build/docker/cortx-all/README.md
> +    Ensure that container is started and we can download RELEASE.INFO
OK

2022-04-21 13:12 UTC, mukul-seagate11 commented on doc/community-build/docker/cortx-all/README.md
> +    - Use below command to build cortx-all image. Enure you are in `cortx-re/docker/cortx-deploy/` directory:
Enure should be Ensure

2022-04-22 02:47 UTC, mukul-seagate11 approved these changes
looks good, hence merging

2022-04-22 03:45 UTC, merged