CORTX-32948: OVA Release Instructions
Seagate/cortx pull request #1644
Opened 2022-09-08 09:12 UTC by mukul-seagate11

### Describe your changes in brief
OVA Release Instructions as per latest release

`[root@cortx-ova ~]# kubectl get pod -o wide -n cortx
NAME                             READY   STATUS    RESTARTS        AGE     IP                NODE                    NOMINATED NODE   READINESS GATES
cortx-consul-client-2hds6        1/1     Running   1 (4h57m ago)   5h17m   192.168.220.157   cortx-ova.seagate.com   <none>           <none>
cortx-consul-server-0            1/1     Running   1 (4h57m ago)   5h17m   192.168.220.152   cortx-ova.seagate.com   <none>           <none>
cortx-control-6bb49c5b68-z88h8   1/1     Running   1 (4h57m ago)   5h17m   192.168.220.149   cortx-ova.seagate.com   <none>           <none>
cortx-data-g0-0                  3/3     Running   3 (4h57m ago)   5h17m   192.168.220.148   cortx-ova.seagate.com   <none>           <none>
cortx-ha-65494bd5c9-fpxgv        3/3     Running   3 (4h57m ago)   5h17m   192.168.220.151   cortx-ova.seagate.com   <none>           <none>
cortx-kafka-0                    1/1     Running   1 (4h57m ago)   5h17m   192.168.220.155   cortx-ova.seagate.com   <none>           <none>
cortx-server-0                   2/2     Running   3 (19m ago)     5h17m   192.168.220.158   cortx-ova.seagate.com   <none>           <none>
cortx-zookeeper-0                1/1     Running   1 (4h57m ago)   5h17m   192.168.220.147   cortx-ova.seagate.com   <none>           <none>
 
[root@cortx-ova ~]# curl --request POST "https://$IPADDRESS:31169/api/v2/login?debug" --header 'Content-Tycation/json' -d '{"username":"cortxadmin","password":"Cortxadmin@123"}' -k
{"reset_password": false}`

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [x] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [x] tested locally
 - [ ] added new dependencies
 - [x] updated the docs
 - [ ] added a test

2022-09-08 11:43 UTC, shailesh-vaidya requested changes

2022-09-08 11:43 UTC, shailesh-vaidya commented on .gitmodules
> +[submodule "cortx-cc"]
Please remove this from PR

2022-09-08 11:45 UTC, mukul-seagate11 commented on .gitmodules
> +[submodule "cortx-cc"]
removed

2022-09-08 11:48 UTC, shailesh-vaidya approved these changes

2022-09-08 12:00 UTC, merged

2022-09-13 12:09 UTC, hessio commented
Can we please also test that the OVA is working from a remote machine also before merging the new release? One of the issues we mentioned for this new OVA was that the ports for the OVA be more inline with industry standard (http: 80 and https: 443)

2022-09-14 15:55 UTC, mukul-seagate11 commented
@hessio, Its actually not in the requirement as current OVA designed & build for 1N with 1 S3 instance