Create tensorflow.md
Seagate/cortx pull request #495
Opened 2020-12-04 18:20 UTC by justinzw

Added tensorflow integration instructions

Signed-off-by: Justin Woo <justin.woo@seagate.com>

2020-12-04 18:54 UTC, johnbent requested changes
Hey Justin,

A few requests; please see inline comments.  Also, can you please add a link to this from the top-level integration page: https://github.com/Seagate/cortx/blob/main/doc/integrations/README.rst?

2020-12-04 18:54 UTC, johnbent commented on doc/integrations/tensorflow.md
> +**What is tensorflow?** tensorflow is an end-to-end open source machine learning platform. The core open source library to help you develop and train ML models. More information can be found here: ht
Can you make this be a proper link please?

2020-12-04 18:54 UTC, johnbent commented on doc/integrations/tensorflow.md
> +Check out this jupyter notebook example of using tensorflow with CORTX using boto3.
Does there need to be a link here?

2020-12-04 18:54 UTC, johnbent commented on doc/integrations/tensorflow/beginner.ipynb
> +{
How is this file linked from the parent file?

2020-12-28 08:00 UTC, mukul-seagate11 commented
@Saumya-Sunder, Can you verify & link the same as suggested?

2021-01-05 03:33 UTC, mukul-seagate11 commented
@Saumya-Sunder, please verify & update as suggested

2021-10-04 15:49 UTC, johnbent commented
Too old. Cleaning up.

2021-10-04 15:49 UTC, closed without merging