Update LocalVMSetup.md
Seagate/cortx pull request #560
Opened 2021-01-13 12:32 UTC by hessio

I added some steps on how to configure your network settings.

2021-01-13 12:56 UTC, andriytk commented on doc/LocalVMSetup.md
> +This setup should take you roughly 20 to 30 minutes
Missed dot at the end of the sentence.

2021-01-13 12:56 UTC, andriytk commented on doc/LocalVMSetup.md
> +## 5. Connect to your VM using Putty
Putty is spelled "PuTTY" correctly (according to [their site](https://www.chiark.greenend.org.uk/~sgtatham/putty/)). But I don't think we should limit users to PuTTY only. We can only suggest it.

2021-01-13 12:56 UTC, andriytk commented on doc/LocalVMSetup.md
> +    yum insatll git
Looks like typo in the command.

2021-01-13 16:15 UTC, huanghua78 commented on doc/LocalVMSetup.md
> +Get the ip address of your VM sudo nmcli will provide you with the ip address. Copy the ip address to your PuTTY console and click connect.
* This step says "connect to your VM", but does not say what to do after connecting to your VM.

* The "Optional" is confusing. The PuTTY is optional? This step is optional?

* We are not assuming people using MS Windows platform. 
   If this step is necessary, please modify it as:
   Connect to your VM using your favorite ssh client.

```
Get the ip address of your VM.  *sudo nmcli*  will provide you with the ip address.
```

2021-01-13 16:24 UTC, huanghua78 commented on doc/LocalVMSetup.md
> +    yum install git
* This is not a MUST-HAVE. If people are trying to install CORTX from PRMs, they don't need "git".
* If sudo is needed in modified step 4, then sudo is needed here, too.

2021-01-14 08:12 UTC, shailesh-vaidya commented
@hessio Thanks for your contribution. Please fix [DCO check](https://github.com/Seagate/cortx/pull/560/checks?check_run_id=1700514046) reported by DCO bot.

2021-01-14 09:54 UTC, andriytk requested changes

2021-01-14 09:54 UTC, andriytk commented on doc/LocalVMSetup.md
> +     sudo nmcli d
Use markup for the commands:

```sh
sudo nmcli d
```

2021-01-14 09:55 UTC, andriytk commented
Please fix the issues mentioned by @huanghua78 also.

2021-01-14 12:31 UTC, andriytk requested changes

2021-01-14 12:31 UTC, andriytk commented on doc/LocalVMSetup.md
> +if you have a network connection then skip on to step 4, otherwise follow the below commands:
Which step 4?

2021-01-14 12:31 UTC, andriytk commented on doc/LocalVMSetup.md
> +run a test to check if you are connected to the network
Start the sentence with a capital letter. Consider adding a colon `:` at the end here.

2021-01-18 10:13 UTC, andriytk approved these changes
Seems OK.

2021-02-02 09:23 UTC, mukul-seagate11 commented
@all-contributors please add @hessio for network

2021-02-02 09:25 UTC, mukul-seagate11 commented
@all-contributors please add @hessio for network

2021-02-02 09:55 UTC, mukul-seagate11 commented
@all-contributors please add @hessio for code

2021-02-24 12:10 UTC, mukul-seagate11 commented
Seems, https://github.com/Seagate/cortx/pull/546 is duplicate PR

2021-02-24 12:15 UTC, hessio commented
I feel as though we should close this as I made this within my few weeks starting here and I don't believe it is useful, nor does it make that much sense.

2021-02-26 07:29 UTC, closed without merging