Formatted Document based on ticket
Seagate/cortx pull request #781
Opened 2021-02-18 00:50 UTC by Saumya-Sunder

Formatted Document based on ticket https://github.com/Seagate/cortx/issues/706

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

2021-02-18 04:50 UTC, mukul-seagate11 approved these changes
looks good

2021-02-18 23:50 UTC, johnbent commented
Please put all of these into one collapsible section:

![](https://user-images.githubusercontent.com/2047294/108436829-6a61d280-7209-11eb-9f18-81b0d8fc9f25.png)

2021-02-18 23:51 UTC, johnbent requested changes
Please see my comment and screenshot.

2021-02-19 00:27 UTC, johnbent approved these changes

2021-02-19 00:28 UTC, merged