Update Cluster_Setup.md
Seagate/cortx pull request #830
Opened 2021-03-15 10:59 UTC by yanqingfu

updated the doc: 
fixed two broken links 

Signed-off-by: Yanqing Fu <yanqing.f.fu@seagate.com>

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2021-03-15 11:18 UTC, mukul-seagate11 approved these changes
looks good

2021-03-18 16:40 UTC, johnbent requested changes

2021-03-18 16:40 UTC, johnbent commented on doc/Cluster_Setup.md
> +[these steps](https://github.com/Seagate/cortx/blob/main/doc/SSH_Public_Key.rst).
@yanqingfu , this URL should be relative since it is in the same repo.  Can you change it please?

2021-04-16 15:39 UTC, johnbent approved these changes

2021-04-16 15:39 UTC, johnbent commented on doc/Cluster_Setup.md
> +[these steps](https://github.com/Seagate/cortx/blob/main/doc/SSH_Public_Key.rst).
@yanqingfu , I'm gonna go ahead and merge this but you never actually resolved this.  You have the link being:

[https://github.com/Seagate/cortx/blob/main/doc/SSH_Public_Key.rst](https://github.com/Seagate/cortx/blob/main/doc/SSH_Public_Key.rst)

Which is an absolute link.  It should be a relative link like:

SSH\_Public\_Key.rst

Can you please do another PR to fix this?

2021-04-16 15:39 UTC, merged