Update Release_Build_Creation.rst
Seagate/cortx pull request #899
Opened 2021-04-06 12:44 UTC by vaibhavparatwar

Tested

### Describe your changes in brief

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

2021-04-06 14:33 UTC, shailesh-vaidya requested changes
@vaibhavparatwar  Again DCO issue. Please fix with rebase option as discussed.

2021-04-07 04:31 UTC, vaibhavparatwar commented
> @vaibhavparatwar Again DCO issue. Please fix with rebase option as discussed.

Done

2021-04-07 04:42 UTC, shailesh-vaidya approved these changes

2021-04-15 14:57 UTC, johnbent approved these changes

2021-04-16 15:35 UTC, johnbent approved these changes

2021-04-16 15:35 UTC, merged