Corrected some minor issues
Seagate/cortx pull request #910
Opened 2021-04-13 12:15 UTC by hessio

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

### Describe your changes in brief

### Changes
 - Some minor fixes

### How Has This Been Tested? (Optional)
 - Using AWS

2021-04-14 04:44 UTC, mukul-seagate11 requested changes
@hessio, Can we keep the interfaces as ens32, ens33 & ens34 to keep the uniformity as defined in https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst

2021-04-14 09:46 UTC, hessio commented
Ya sure I can change this, this guide was using OVA 1.0.2 instead of 1.0.3 this is why we had those NIC names but I can change this to use 1.0.3 instead and change the names of the NICs too.

2021-04-14 10:14 UTC, mukul-seagate11 approved these changes
looks good

2021-04-15 14:56 UTC, johnbent approved these changes

2021-04-16 15:50 UTC, johnbent approved these changes

2021-04-16 15:50 UTC, merged