Fixed a formatting error
Seagate/cortx pull request #919
Opened 2021-04-19 18:37 UTC by hessio

Sign-off-by: Patrick Hession <patrick.hession@seagate.com>

### Describe your changes in brief

### Changes
 - Removed extra spaces that prevented an easy copy/paste for the user

2021-04-20 02:27 UTC, huanghua78 commented on doc/ProvisionReleaseBuild.md
> +   yum-config-manager --add-repo "${CORTX_RELEASE_REPO}/3rd_party/"
Apparently, this is wrong.

This change is not needed.
But, we need a fix for the Line 15.
"yum install -y yum-utils" should be on a new line.

2021-04-20 02:27 UTC, huanghua78 requested changes
This fix is wrong.

2021-04-20 02:29 UTC, huanghua78 commented
Also, please fork and clone the "cortx" repo, do some changes, and create new PR.
Not on the Seagate repo.

2021-04-30 12:07 UTC, hessio commented
Duplicate

2021-04-30 12:07 UTC, closed without merging